### ISSUE TITLE
readthedocs api rendering

### ISSUE THREAD

**Issue by ben-cassese** [kmzzhang/nbi#34]
Hello! Thanks for all of your work on this package, I’m planning on incorporating it into some upcoming projects and am excited to see where that goes. One small issue that’s made adopting the package slightly more challenging: it looks like readthedocs isn’t rendering the API documentation. The demos are all fine, but anything made with autodocs is missing.

The problem seems to be a missing requirement in docs/requirements.txt. “wandb” is included as a dependency in pyproject.toml but isn’t in the requirements that are installed when rendering the html pages. Minor thing, and I can build the docs fine locally after installing wandb, but it would be helpful to have a web version of the API docs as a reference. Thanks again!

**Comment by kmzzhang** [comment]
Hi Ben! Thank you very much for the fix. I'm excited to hear that you're planning on incorporating it into your projects.
